"""
quantize_weights.py — Post-Training Quantization for FPGA Deployment

Converts trained float32 SNN weights to 8-bit Q1.7 fixed-point format
and exports them as Xilinx .coe files (BRAM init) and .hex files (simulation).

Q1.7 Format:
  - 8 bits total: 1 sign bit, 0 integer bits, 7 fractional bits
  - Range:      [-1.0, +0.9921875]
  - Resolution: 1/128 = 0.0078125
  - Encoding:   two's complement

Usage:
  python quantize_weights.py
  python quantize_weights.py --model models/snn_best.pth --output weights/
"""

import os
import argparse
import numpy as np
import torch
import torch.nn as nn

# Import the model class from training script
from train_snn import ECG_SNN, NUM_STEPS, load_data

# ─── Q1.7 Fixed-Point Parameters ────────────────────────────────────────────

FRAC_BITS = 7                    # Number of fractional bits
SCALE = 2 ** FRAC_BITS           # = 128
Q_MIN = -128                     # Minimum 8-bit signed value (-1.0 in Q1.7)
Q_MAX = 127                      # Maximum 8-bit signed value (+0.9921875 in Q1.7)

# ─── Quantization Functions ─────────────────────────────────────────────────

def float_to_q17(weights: np.ndarray) -> np.ndarray:
    """
    Convert float32 weights to 8-bit Q1.7 fixed-point (two's complement).
    
    Steps:
        1. Clamp to representable range [-1.0, +0.9921875]
        2. Multiply by 2^7 = 128
        3. Round to nearest integer
        4. Clamp to [-128, +127]
    
    Returns:
        int8 numpy array with quantized values.
    """
    clamped = np.clip(weights, -1.0, Q_MAX / SCALE)
    scaled = clamped * SCALE
    rounded = np.round(scaled).astype(np.int32)
    quantized = np.clip(rounded, Q_MIN, Q_MAX).astype(np.int8)
    return quantized


def q17_to_float(quantized: np.ndarray) -> np.ndarray:
    """Convert Q1.7 int8 values back to float for error analysis."""
    return quantized.astype(np.float32) / SCALE


def quantization_error(original: np.ndarray, quantized_int: np.ndarray) -> dict:
    """Compute quantization error statistics."""
    reconstructed = q17_to_float(quantized_int)
    error = original - reconstructed
    return {
        'max_abs_error': float(np.max(np.abs(error))),
        'mean_abs_error': float(np.mean(np.abs(error))),
        'rmse': float(np.sqrt(np.mean(error ** 2))),
        'clipped_count': int(np.sum((original < -1.0) | (original > Q_MAX / SCALE))),
        'total_weights': int(original.size),
    }


# ─── Export Functions ────────────────────────────────────────────────────────

def to_hex_byte(value: np.int8) -> str:
    """Convert signed int8 to 2-digit hex string (two's complement)."""
    return format(value & 0xFF, '02X')


def export_coe(quantized: np.ndarray, filepath: str, layer_name: str):
    """
    Export quantized weights as a Xilinx .coe file for BRAM initialization.
    
    The weights are stored row-major: for a (M, N) weight matrix,
    the memory layout is: w[0][0], w[0][1], ..., w[0][N-1], w[1][0], ...
    
    Format:
        memory_initialization_radix=16;
        memory_initialization_vector=
        XX, XX, XX, ...;
    """
    flat = quantized.flatten()
    
    with open(filepath, 'w') as f:
        f.write(f"; {layer_name} weights — Q1.7 fixed-point (8-bit signed)\n")
        f.write(f"; Shape: {quantized.shape} — {quantized.size} total values\n")
        f.write(f"; Generated by quantize_weights.py\n")
        f.write(";\n")
        f.write("memory_initialization_radix=16;\n")
        f.write("memory_initialization_vector=\n")
        
        hex_values = [to_hex_byte(v) for v in flat]
        
        # Write 16 values per line for readability
        for i in range(0, len(hex_values), 16):
            chunk = hex_values[i:i+16]
            line = ', '.join(chunk)
            if i + 16 >= len(hex_values):
                line += ';\n'
            else:
                line += ',\n'
            f.write(line)


def export_hex(quantized: np.ndarray, filepath: str, layer_name: str):
    """
    Export quantized weights as a plain .hex file (one value per line).
    Useful for VHDL testbench $readmemh().
    """
    flat = quantized.flatten()
    
    with open(filepath, 'w') as f:
        f.write(f"// {layer_name} weights — Q1.7 fixed-point (8-bit signed)\n")
        f.write(f"// Shape: {quantized.shape} — {quantized.size} total values\n")
        for v in flat:
            f.write(to_hex_byte(v) + '\n')


def export_summary(layer_stats: list, filepath: str):
    """Write a human-readable quantization report."""
    with open(filepath, 'w') as f:
        f.write("=" * 70 + "\n")
        f.write("  QUANTIZATION REPORT — Q1.7 Fixed-Point (8-bit signed)\n")
        f.write("=" * 70 + "\n\n")
        
        total_weights = 0
        total_clipped = 0
        
        for stat in layer_stats:
            f.write(f"Layer: {stat['name']}\n")
            f.write(f"  Shape:          {stat['shape']}\n")
            f.write(f"  Total weights:  {stat['error']['total_weights']}\n")
            f.write(f"  Float range:    [{stat['float_min']:.6f}, {stat['float_max']:.6f}]\n")
            f.write(f"  Clipped values: {stat['error']['clipped_count']}\n")
            f.write(f"  Max |error|:    {stat['error']['max_abs_error']:.6f}\n")
            f.write(f"  Mean |error|:   {stat['error']['mean_abs_error']:.6f}\n")
            f.write(f"  RMSE:           {stat['error']['rmse']:.6f}\n")
            f.write(f"  Files:          {stat['coe_file']}, {stat['hex_file']}\n")
            f.write("\n")
            total_weights += stat['error']['total_weights']
            total_clipped += stat['error']['clipped_count']
        
        f.write("-" * 70 + "\n")
        f.write(f"Total weights quantized: {total_weights}\n")
        f.write(f"Total clipped values:    {total_clipped}\n")
        f.write(f"Max theoretical error:   {1.0 / SCALE / 2:.6f} (half LSB)\n")
        f.write("=" * 70 + "\n")


# ─── Accuracy Validation ────────────────────────────────────────────────────

def validate_quantized_accuracy(model_path: str):
    """
    Compare float32 model accuracy vs quantized model accuracy on the test set.
    This catches cases where quantization error degrades classification.
    """
    device = torch.device("cpu")
    
    # Load test data
    _, test_loader, _ = load_data()
    
    # Load original float model
    net_float = ECG_SNN().to(device)
    net_float.load_state_dict(torch.load(model_path, map_location=device, weights_only=True))
    net_float.eval()
    
    # Create quantized model (apply quantization to weights in-place)
    net_quant = ECG_SNN().to(device)
    net_quant.load_state_dict(torch.load(model_path, map_location=device, weights_only=True))
    
    with torch.no_grad():
        for name, param in net_quant.named_parameters():
            w_np = param.cpu().numpy()
            q_int = float_to_q17(w_np)
            q_float = q17_to_float(q_int)
            param.copy_(torch.tensor(q_float))
    
    net_quant.eval()
    
    # Evaluate both
    results = {}
    for label, net in [("Float32", net_float), ("Quantized Q1.7", net_quant)]:
        correct = 0
        total = 0
        with torch.no_grad():
            for data, targets in test_loader:
                data = data.to(device)
                targets = targets.to(device)
                spk_out, _ = net(data)
                _, predicted = spk_out.sum(dim=0).max(1)
                total += targets.size(0)
                correct += (predicted == targets).sum().item()
        acc = 100.0 * correct / total
        results[label] = acc
        print(f"  {label:20s} accuracy: {acc:.2f}%")
    
    drop = results["Float32"] - results["Quantized Q1.7"]
    print(f"  {'Accuracy drop':20s}:  {drop:+.2f}%")
    return results


# ─── Main ────────────────────────────────────────────────────────────────────

def quantize(model_path: str, output_dir: str):
    """Main quantization pipeline."""
    
    os.makedirs(output_dir, exist_ok=True)
    
    print(f"Loading trained model from: {model_path}")
    state_dict = torch.load(model_path, map_location='cpu', weights_only=True)
    
    # Layer mapping: parameter name → human-readable name
    layer_info = {
        'fc1.weight': ('fc1_hidden1', '128 → 16'),
        'fc2.weight': ('fc2_hidden2', '16 → 16'),
        'fc3.weight': ('fc3_output',  '16 → 5'),
    }
    
    layer_stats = []
    
    print("\n" + "=" * 60)
    print("  Quantizing weights to Q1.7 (8-bit signed fixed-point)")
    print("=" * 60)
    
    for param_name, (file_prefix, desc) in layer_info.items():
        if param_name not in state_dict:
            print(f"\n⚠ Warning: '{param_name}' not found in model — skipping.")
            continue
        
        w_float = state_dict[param_name].numpy()
        
        print(f"\n  Layer: {param_name} ({desc})")
        print(f"    Shape:       {w_float.shape}")
        print(f"    Float range: [{w_float.min():.6f}, {w_float.max():.6f}]")
        
        # Quantize
        w_q17 = float_to_q17(w_float)
        error = quantization_error(w_float, w_q17)
        
        print(f"    Clipped:     {error['clipped_count']} / {error['total_weights']}")
        print(f"    Max |err|:   {error['max_abs_error']:.6f}")
        print(f"    RMSE:        {error['rmse']:.6f}")
        
        # Export files
        coe_path = os.path.join(output_dir, f"{file_prefix}.coe")
        hex_path = os.path.join(output_dir, f"{file_prefix}.hex")
        
        export_coe(w_q17, coe_path, f"{param_name} ({desc})")
        export_hex(w_q17, hex_path, f"{param_name} ({desc})")
        
        print(f"    Exported:    {coe_path}")
        print(f"                 {hex_path}")
        
        layer_stats.append({
            'name': f"{param_name} ({desc})",
            'shape': str(w_float.shape),
            'float_min': float(w_float.min()),
            'float_max': float(w_float.max()),
            'error': error,
            'coe_file': os.path.basename(coe_path),
            'hex_file': os.path.basename(hex_path),
        })
    
    # Write summary report
    report_path = os.path.join(output_dir, "quantization_report.txt")
    export_summary(layer_stats, report_path)
    print(f"\n  Report saved: {report_path}")
    
    # Validate accuracy (only if test data is available)
    print("\n" + "=" * 60)
    print("  Validating quantized accuracy on test set")
    print("=" * 60)
    try:
        validate_quantized_accuracy(model_path)
    except FileNotFoundError:
        print("  ⚠ Test data (data/*.npy) not found — skipping accuracy validation.")
        print("    Run preprocess.py first if you want accuracy comparison.")
    
    print("\n✓ Quantization complete!")
    print(f"  Output directory: {output_dir}")
    print(f"  Files generated:  {len(layer_stats)} × (.coe + .hex) + report")
    

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Quantize SNN weights to Q1.7 for FPGA")
    parser.add_argument('--model', type=str, default='models/snn_best.pth',
                        help='Path to trained model checkpoint')
    parser.add_argument('--output', type=str, default='weights',
                        help='Output directory for quantized weight files')
    args = parser.parse_args()
    
    quantize(args.model, args.output)
